### PR TITLE
Fix test, migrate to mocha, enable travis

### LINKED ISSUE #271: Fix tests, migrate to mocha and add Travis

### PR DESCRIPTION
**Pull request by kanitw**
**please merge #296, https://github.com/uwdata/vega-lite-ui/pull/15 and publish `vega-lite-ui@0.7.8` first** 

- fixes #271 
- also fixes https://github.com/uwdata/vega-lite-ui/issues/14

### CODE REVIEW

**Comment by kanitw** [comment]
@domoritz  I just merged your change in master into this branch.

**Comment by domoritz** [comment]
I get a bunch of errors when I start the app. Does everything work for you? Can you reinstall all the bower and npm dependencies to see whether things are breaking?

**Comment by kanitw** [comment]
It’s just outdated vlui version. It should work now.  Let me know if it’s still broken.

**Comment by domoritz** [comment]
I can't test right now because the wifi doesn't allow git. I'll merge when I get back or you can test and merge. The code looks fine.

**Comment by domoritz** [comment]
There is a bug with the nominal stuff. If you change to "text-ordinal" and then change the aggregation, it selects number.

**Comment by domoritz** [comment]
Which also happens in master.

**Comment by kanitw** [comment]
Can u create an issue?



—
Kanit "Ham" Wongsuphasawat
http://kanitw.yellowpigz.com/ 


Painfully tapped iPhone keyboard--only for you.  Sorry for brevity and typos.

**Comment by domoritz** [comment]
See #299

**Pull request merged**
