### PR TITLE
Use vega from bower

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
bower ECONFLICT     Unable to find suitable version for lodash    in travis

**Comment by domoritz** [comment]
I believe this is because we haven't pushed the latest vl ui.

**Comment by domoritz** [comment]
Jep, that was the issue. Travis is passing now.

**Comment by domoritz** [comment]
Also fixes issues similar to https://github.com/uwdata/voyager/issues/163

**Pull request merged**
